//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 09:45:19 AM CET 
//


package com.amazonaws.ec2.doc._2010_08_31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DescribeSpotPriceHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeSpotPriceHistoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="instanceTypeSet" type="{http://ec2.amazonaws.com/doc/2010-08-31/}InstanceTypeSetType" minOccurs="0"/>
 *         &lt;element name="productDescriptionSet" type="{http://ec2.amazonaws.com/doc/2010-08-31/}ProductDescriptionSetType" minOccurs="0"/>
 *         &lt;element name="filterSet" type="{http://ec2.amazonaws.com/doc/2010-08-31/}FilterSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeSpotPriceHistoryType", propOrder = {
    "startTime",
    "endTime",
    "instanceTypeSet",
    "productDescriptionSet",
    "filterSet"
})
public class DescribeSpotPriceHistoryType {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    protected InstanceTypeSetType instanceTypeSet;
    protected ProductDescriptionSetType productDescriptionSet;
    protected FilterSetType filterSet;

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the instanceTypeSet property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceTypeSetType }
     *     
     */
    public InstanceTypeSetType getInstanceTypeSet() {
        return instanceTypeSet;
    }

    /**
     * Sets the value of the instanceTypeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceTypeSetType }
     *     
     */
    public void setInstanceTypeSet(InstanceTypeSetType value) {
        this.instanceTypeSet = value;
    }

    /**
     * Gets the value of the productDescriptionSet property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDescriptionSetType }
     *     
     */
    public ProductDescriptionSetType getProductDescriptionSet() {
        return productDescriptionSet;
    }

    /**
     * Sets the value of the productDescriptionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDescriptionSetType }
     *     
     */
    public void setProductDescriptionSet(ProductDescriptionSetType value) {
        this.productDescriptionSet = value;
    }

    /**
     * Gets the value of the filterSet property.
     * 
     * @return
     *     possible object is
     *     {@link FilterSetType }
     *     
     */
    public FilterSetType getFilterSet() {
        return filterSet;
    }

    /**
     * Sets the value of the filterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterSetType }
     *     
     */
    public void setFilterSet(FilterSetType value) {
        this.filterSet = value;
    }

}
