//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 09:45:19 AM CET 
//


package com.amazonaws.ec2.doc._2010_08_31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LaunchPermissionOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LaunchPermissionOperationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="add" type="{http://ec2.amazonaws.com/doc/2010-08-31/}LaunchPermissionListType"/>
 *         &lt;element name="remove" type="{http://ec2.amazonaws.com/doc/2010-08-31/}LaunchPermissionListType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LaunchPermissionOperationType", propOrder = {
    "add",
    "remove"
})
public class LaunchPermissionOperationType {

    protected LaunchPermissionListType add;
    protected LaunchPermissionListType remove;

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link LaunchPermissionListType }
     *     
     */
    public LaunchPermissionListType getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaunchPermissionListType }
     *     
     */
    public void setAdd(LaunchPermissionListType value) {
        this.add = value;
    }

    /**
     * Gets the value of the remove property.
     * 
     * @return
     *     possible object is
     *     {@link LaunchPermissionListType }
     *     
     */
    public LaunchPermissionListType getRemove() {
        return remove;
    }

    /**
     * Sets the value of the remove property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaunchPermissionListType }
     *     
     */
    public void setRemove(LaunchPermissionListType value) {
        this.remove = value;
    }

}
